### ISSUE TITLE
Use and advantage of the `venv` modul

### ISSUE THREAD

**Issue by philippabele** [philippabele/angular-contact-with-tensorflow#13]
Start using the `venv` modul in order to work in a virtual environment.

https://docs.python.org/3/library/venv.html

https://realpython.com/python-virtual-environments-a-primer/

The idea is, to have for each git project your own python environment and
to separate the used libraries as well as not mixing dependencies.

Keep in mind to add the folder of your environment to your gitignore file and keep your git repository clean.

**Comment by Roccozzz** [comment]
@philippabele this issue is already resolved in philippabele/angular-contact-with-tensorflow. I can't create a new pull request because the venv already exists in the main branch, so i think this issue should be closed.
