### ISSUE TITLE
Make use of a requirements.txt file

### ISSUE THREAD

**Issue by philippabele** [philippabele/angular-contact-with-tensorflow#14]
By using a requirements file, you make your used dependencies explicit. Additionally, you will be able to restore your virtual python environment easily.

https://learnpython.com/blog/python-requirements-file/

https://realpython.com/lessons/using-requirement-files/

**Comment by philippabele** [comment]
@Roccozzz It looks like you have solved this issues in your repository [Roccozzz/angular-contact-with-tensorflow](https://github.com/Roccozzz/angular-contact-with-tensorflow), but missed to PR into [philippabele/angular-contact-with-tensorflow](https://github.com/philippabele/angular-contact-with-tensorflow)

Please take a look at the other open issues in philippabele/angular-contact-with-tensorflow !

**Comment by Roccozzz** [comment]
@philippabele the requirements.txt file is already in philippabele/angular-contact-with-tensorflow main branch because it was added via the add-venv branch. I can't create a new pull request for this issue because it doesn't update the main branch, so i think this issue should be closed.
